//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Init.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Init.Web.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось сбросить пароль.
        /// </summary>
        internal static string msgFailToResetPassword {
            get {
                return ResourceManager.GetString("msgFailToResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Требуется указать ответ на секретный вопрос..
        /// </summary>
        internal static string msgNeedSecretAnswer {
            get {
                return ResourceManager.GetString("msgNeedSecretAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Требуется указать секретный вопрос..
        /// </summary>
        internal static string msgNeedSecretQuestion {
            get {
                return ResourceManager.GetString("msgNeedSecretQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Эта функция поддерживается только в случае уникальности электронной почты.
        /// </summary>
        internal static string msgNeedUniqueEMail {
            get {
                return ResourceManager.GetString("msgNeedUniqueEMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сброс пароля отменен.
        /// </summary>
        internal static string msgPasswodResetRejected {
            get {
                return ResourceManager.GetString("msgPasswodResetRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось сбросить паролью Сгенерированный пароль не соответствует политике безопасности.
        /// </summary>
        internal static string msgPasswordFormatIncorrect {
            get {
                return ResourceManager.GetString("msgPasswordFormatIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запрос пароля запрещен политикой безопасности..
        /// </summary>
        internal static string msgPasswordRequestForbidden {
            get {
                return ResourceManager.GetString("msgPasswordRequestForbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сброс пароля запрещен политикой безопасности..
        /// </summary>
        internal static string msgPasswordResetForbidden {
            get {
                return ResourceManager.GetString("msgPasswordResetForbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Восстановление пароля невозможно..
        /// </summary>
        internal static string msgPasswordRetrievingImposible {
            get {
                return ResourceManager.GetString("msgPasswordRetrievingImposible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь не найден.
        /// </summary>
        internal static string msgUserNotFound {
            get {
                return ResourceManager.GetString("msgUserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный ответ на секретный вопрос.
        /// </summary>
        internal static string msgWrongSecretAnswer {
            get {
                return ResourceManager.GetString("msgWrongSecretAnswer", resourceCulture);
            }
        }
    }
}
